### ISSUE TITLE
Exposed Apache htpasswd file

### ISSUE THREAD

**Issue by nicht** [pikvm/kvmd#1]
Potential security breach. See /configs/kvmd/htpasswd

**Comment by mdevaev** [comment]
It has limited permissions (600) and readable only by root and kvmd group. What exactly is the problem?

**Comment by nicht** [comment]
I saw the creds in the htpasswd file and thought it was a mistake publishing it on a open source repo, usually this kinda of stuff is inside a environment variable to not be exposed to public. 

I wanted to report it before anyone else would abuse of this breach. 

If your project has a different structure and this indeed needed to be publish, then it's ok.

**Comment by mdevaev** [comment]
Ah, I get it. Thank you for your concern! Everything is fine. This file contains default settings that change during installation.
