### ISSUE TITLE
Feature - maximizing window

### ISSUE THREAD

**Issue by arykov** [pikvm/kvmd#14]
As discussed [here](https://discord.com/channels/580094191938437144/580094193834131456/758069937112744136) I am looking for a way to maximize use of screen real estate by maximizing streaming window.

**Comment by arykov** [comment]
Here's my prototype of scaling and full screen code: https://github.com/arykov/kvmd/commits/master
Could you have a look to see if you find anything offensive?
Known issues:
1) and most important I am still waiting for parts to test this on real build. So there are a lot of unknowns for mouse alignment and keyboard
2) Testing of video resolution change has not been done.  "Auto resize stream" off does not work(can we get rid of it so it is always on?). The best way of testing it would be using v4l2 loopback, which I have not been able to make work yet(https://discord.com/channels/580094191938437144/580094193834131456/760483352246616105). 
3) ESC in full chrome screen mode cannot be intercepted and will
4) Only played with it in Chrome on W10. There clearly will be issues related to IPad resolutions since there are non overridable values, that will prevent hiding top of the window

**Comment by mdevaev** [comment]
Work is underway in this branch: https://github.com/pikvm/kvmd/tree/wm

**Comment by arykov** [comment]
Take 2

**Comment by mdevaev** [comment]
Done
