### ISSUE TITLE
Brainstorming on race condition with __ensureStream resulting in multiple mjpeg loads

### ISSUE THREAD

**Issue by aggieNick02** [pikvm/kvmd#17]
This doesn't cause any noticeable harm, but I noticed it happening a decent amount when using kvmd with a capture process running on another machine (so not the standard pikvm setup). I then played a bit and was able to make it happen in the standard pikvm setup, just less often. Wanted to know what you think. Happy to implement a fix, or you can just close the issue if you don't think it's worth addressing.

What can happen is the following:

1. `__ensureStream` leads to setting `src` on `stream-image`
2. `__ensureStream` is called again with a state generated before the mjpeg request was received and/or fully processed by ustreamer. This results in `src` being set again on `stream-image`, and the first mjpeg request being cancelled and a new one being issued.

This is a little bit wasteful. If you are playing with things in a debugger, you can really make it obvious by putting a breakpoint in `__ensureStream` where `__client_id` is set based off the cookie. Step over that line, then set `clients_stat` to `{}` and then continue. (This simulates a single stale state.) In the time it takes to do this, several states will have queued, and as each one is processed, the `src` of the `stream-image` will be reset. If you then look in the network tab in chrome, you'll see the many cancelled mjpeg requests.

Again, this stabilizes, but it would be great if we could avoid any unneeded `src` resets on `stream-image`.

Any thoughts? We could store the time the `stream-image` `src` is set and then not reset it if a few seconds have not elapsed. This would give the server enough time to receive the mjpeg request and reflect it in its state response as long as the server is not super-overloaded.

Another idea is to use the `complete` property on `stream-image`. I think that makes things better but is still not foolproof though as the polled state could have been generated before the image was complete but received after.

**Comment by mdevaev** [comment]
A bug is a bug, no matter what it is. Bugs need to be fixed.

Give me some time to think about it. I want to understand which solution will be better.

**Comment by aggieNick02** [comment]
Was thinking about this a little bit. There are actually two related race conditions here.

The first is what I described before. `__ensureStream` may be passing a stale `clients_stat`, causing an unnecessary extra set of `src` on `stream-image`.

The second is that even if `clients_stat` is not stale, the `stream_client` cookie may not yet be set if the initial portion of the mjpeg response has not been processed.

There are two communication channels involved. The websocket is unidirectional and periodically sending ustreamer state to `stream.js` The `stream-image` is the other channel and allows for "sending" to ustreamer by setting `src` and receiving from ustreamer by checking for the `stream_client` cookie and all of the images. But we only check for the cookie when prompted by messages from the first channel, and that can occur before the cookie has been set/received.

The goal of the cookie and state checking is to detect when the mjpeg connection has been lost, There are some thoughts on this problem here: https://stackoverflow.com/questions/18844735/how-do-i-detect-a-disconnect-from-an-mjpeg-stream-in-javascript. The answer by 01BTC10 seems like it would work, but then instead of the browser doing the mjpeg work the javascript does it - no idea if there is a performance hit that would matter there.

It's a shame there's not something exposed via an img property to reveal when the connection is lost, since the browser knows this. Other than the stackoverflow idea above, I've not been able to really find anything else besides not resetting the first few seconds after stream-image is set like I mentioned initially. I'll keep thinking about it.

**Comment by mdevaev** [comment]
I don't like the idea of using JS for something that can be done in a native way.

I understand that this is probably a bad way to solve the problem, but can I add a delay between the img update and the first check?

**Comment by aggieNick02** [comment]
I totally understand not wanting to basically redo mjpeg support by parsing/setting the img in javascript - there could be all kinds of issues with that (latency could increase, framerate could be worse) - having the browser do all the mjpeg stuff natively is nice.

I think a delay or grace period after setting src on image and before the first validation check would be good.

**Comment by mdevaev** [comment]
Okay, I'll take care of that when I've sorted out the main things on the v3 board project. Probably in the next few weeks.

**Comment by aggieNick02** [comment]
Sounds good. Thank you very much.

**Comment by mdevaev** [comment]
I haven't forgotten about this problem. Should now be fixed, will be available in the next release.
